### ISSUE TITLE
Rsync connection large files

### ISSUE THREAD

**Issue by maustin-ixis** [tg123/sshpiper#3] opened 2016-01-11 16:17 UTC
Hello,

When using Rsync to transfer large files (1GB+) from remote to local over SSHPiper it proceeds as far as 99% and then the connection terminates.  Reviewing the logs from SSHPiper I can see the following error was output;

    closed reason: ssh: only handshakeTransport can send newKeys

If I test with a smaller file (512MB) the transfer completes sucesfully and does not terminate.

Thanks.

**Comment by tg123** [comment] 2016-01-12 08:18
I will check it, thanks for reporting

**Comment by tg123** [comment] 2016-01-23 18:19
Hi @maustin-ixis 

reproduced every time?
LAN or WAN?

**Comment by ixishostingrundeck** [comment] 2016-01-25 09:35
Hello @tg123,

Yes this can be reproduced every time when using Rsync.  I have tested with scp and this technically completes, though at the end of the transfer the connection is terminated resulting in scp displaying and error message that the connection was halted.

Everything seems to work fine with a smaller file e.g. 512mb, however it appears that anything over 900mb has the issue.  I have amended the keep-alive settings ensure it is sent every 60 seconds, however the problem still persists.

I have tested this in multiple setups using the docker image and without.  In all cases the results are the same, the connection terminates at the end of the transfer.

I have also tested this on both Linux (Debian) and OSX, the problem is the same on both operating systems.  For reference this has only been tested on a WAN connection.

**Comment by maustin-ixis** [comment] 2016-01-25 09:37
Hello @tg123,

Yes this can be reproduced every time when using Rsync. I have tested with scp and this technically completes, though at the end of the transfer the connection is terminated resulting in scp displaying and error message that the connection was halted.

Everything seems to work fine with a smaller file e.g. 512mb, however it appears that anything over 900mb has the issue. I have amended the keep-alive settings ensure it is sent every 60 seconds, however the problem still persists.

I have tested this in multiple setups using the docker image and without. In all cases the results are the same, the connection terminates at the end of the transfer.

I have also tested this on both Linux (Debian) and OSX, the problem is the same on both operating systems. For reference this has only been tested on a WAN connection.

**Comment by 0x0F2** [comment] 2016-05-22 19:48
I have hit the same issues as well. It is independent of the network type.

For SSHv2 connections, the session key is auto renegotiated after some some large number of packets have been sent or some amount of time has elapsed. These defaults are specific to the cypher being used. This renegotiation could be triggered by the server or client. For me, this occurs after 1GB of TOTAL data transfer over rsync (all individual files < 1GB).  

I have tried every workaround I can think of. The most hopeful was setting "RekeyLimit 2G 36000" for host and client endpoints (/etc/sshd_conf and ~/.ssh/config). Oddly, this had no effect and the transfer still gets closed after 1GB. I know these settings are getting read by sshd because when I set them to absurdly large values, i.e. 1000G, I get the message "RekeyLimit too large".

The error itself "only handshakeTransport can send newKeys" comes out of GO's ssh implementation. I do not know and I have not tested the native GO implementation, but I would assume that because key renegotiation is a part of the SSHv2 spec, that this implementation would fully support this. I'm guessing that because sshpiper has to man-in-the-middle the SSH connection that there is some extra work that needs to be done to handle the renegotiation. I have not looked at the code so this is just wild speculation. 

In any case, thanks for putting this project together. sshpiper has been super useful to me.

**Comment by 0x0F2** [comment] 2016-08-08 14:11
Hi @tg123,

Is this issue out of scope for sshpiper? Shall this be taken upstream to those that have implemented the ssh library or are you the appropriate contact? Is this something that has the possibility of being fixed or is it impossible due to how ssh connections are handled? Let me know if this is a WontFix.

**Comment by tg123** [comment] 2016-08-08 17:27
really sorry about the slowness. I am busy since the start of this year.
I will check later

**Comment by 0x0F2** [comment] 2016-08-08 17:40
Oh, no rush at all!  I'm just happy that such a tool exists and continue to get a lot of use from it. No worries.

**Comment by tg123** [comment] 2016-09-03 16:48
seems caused by key re-exchange which is not support by sshpiper at the moment.
I will try to fix it.

Thanks

**Comment by tg123** [comment] 2016-09-03 18:47
fixed after sync with latest golang.org/x/crypto/ssh

see also
https://github.com/golang/crypto/commit/b76c864ef1dca1d8f271f917c290cddcce3d9e0d

**Closed by tg123** 2016-09-03 18:47 UTC

**Comment by 0x0F2** [comment] 2016-09-09 14:04
tg123,

I have deployed the latest version and everything now works as expected, even with extremely large files. Thank you for taking a look at this, I really appreciate it. The additional logging is an excellent addition as well.
