### ISSUE TITLE
Can you use ed25519 algo and make rsa deprecated

### ISSUE THREAD

**Issue by Elrondo46** [tg123/sshpiper#80] opened 2021-11-10 06:22 UTC
ssh-rsa is the default option for host keys in your tool, can you make ed25519 as default algo. RSA is deprecated in 2021

**Comment by shiipou** [comment] 2021-11-10 07:47
It's just rsa with sha-1 that is deprecated in 2021.
You can safely use SHA-2 rsa algorithm.

**Comment by opteamax** [comment] 2022-02-21 22:43
Unfortunately many clients reject connecting also with SHA-2 rsa with complaining 

no matching host key type found. Their offer: ssh-rsa

as this algorithm fell of the clients acceptable connections. Making ed25519 default would also be highly appreciated on our side as we receive many client complaints.

**Comment by shiipou** [comment] 2022-02-22 08:20
> Unfortunately many clients reject connecting also with SHA-2 rsa with complaining
> 
> no matching host key type found. Their offer: ssh-rsa
> 
> as this algorithm fell of the clients acceptable connections. Making ed25519 default would also be highly appreciated on our side as we receive many client complaints.

You can add the following option to your SSH client : `-oHostKeyAlgorithms=+ssh-dss`

But if you can't add this option, you can create the file at path `$HOME/.ssh/config`
and adding the following using your own ip : 
```
Host nas
  HostName 192.168.x.x
  HostKeyAlgorithms=+ssh-dss
```

~~Some client won't take this file but that tell you that's a bad client ^^~~

**Comment by tg123** [comment] 2022-02-25 23:06
> Unfortunately many clients reject connecting also with SHA-2 rsa with complaining
> 
> no matching host key type found. Their offer: ssh-rsa
> 
> as this algorithm fell of the clients acceptable connections. Making ed25519 default would also be highly appreciated on our side as we receive many client complaints.

do you mean make -i `/etc/ssh/ssh_host_rsa_key` default?

**Comment by bhperry** [comment] 2022-03-09 00:31
Regardless of default, it seems that ssh-rsa is the _only_ accepted host key algorithm. This is causing failures with newer versions of openssh-client (I believe it's anything after 8.5p1), with the error `client_global_hostkeys_private_confirm: server gave bad signature for RSA key 0`

Is there a way to configure a different set of allowed algorithms? Have been digging in to see if I can find where this is set, but no luck so far.

**Comment by bhperry** [comment] 2022-03-09 17:47
Poked around in sshpiper.crypto a bit and realized that the primary changes to support SHA256 and SHA512 signing with RSA keys is already merged in from upstream, there just hasn't been a new tag made since 2020.

Tested a build of sshpiper with go.mod pointed to the latest commit of sshpiper.crypto, and confirmed that it does now select SHA512 instead of SHA1 with an RSA host key.

**Comment by tg123** [comment] 2022-03-09 18:32
@bhperry latest master is always using latest `sshpiper.crypto`
which version are you using?

**Comment by bhperry** [comment] 2022-03-09 19:05
Oh, right you are. Working off of a fork of sshpiper, so we're a bit out of sync with master. Thanks!

**Comment by tg123** [comment] 2022-03-10 05:40
@bhperry thanks for confirming. grpc driver would decouple the logic and sshpiper
let me know if it could help to get rid of your private build

**Closed by tg123** 2022-03-10 05:40 UTC

**Comment by bhperry** [comment] 2022-03-10 15:53
Fork was for something else. These PRs my colleague made
https://github.com/tg123/sshpiper/pull/77
https://github.com/pockost/sshpipe-k8s-lib/pull/1

Would like to merge our forks if you have the time to review. Happy to get up to date with master and reopen the PRs.
